# Generated by Django 6.0 on 2026-01-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralLinks', '0002_remove_link_user_id_remove_paquetes_uder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='package',
        ),
        migrations.DeleteModel(
            name='Paquetes',
        ),
    ]
