# Generated by Django 6.0 on 2026-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralLinks', '0003_remove_link_package_delete_paquetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='protected_link',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='word_key',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
