# Generated by Django 6.0 on 2026-01-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralLinks', '0004_alter_link_description_alter_link_protected_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='protected_link',
        ),
        migrations.RemoveField(
            model_name='link',
            name='word_key',
        ),
    ]
